// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUR9WiMEjos2Xx2_LfsTBSb93QAwwmg2M',
    appId: '1:542980836794:web:bd24835b7f51cb8f4b2183',
    messagingSenderId: '542980836794',
    projectId: 'rxmed0',
    authDomain: 'rxmed0.firebaseapp.com',
    storageBucket: 'rxmed0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-fqNmJlUFoY70ApRV04kHV8b1pE0bRWk',
    appId: '1:542980836794:android:d94b4b817b0a00ba4b2183',
    messagingSenderId: '542980836794',
    projectId: 'rxmed0',
    storageBucket: 'rxmed0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe-eoItkk-XtFNtwjoAMMl3q0uECVT6LU',
    appId: '1:542980836794:ios:24103a10df5c6add4b2183',
    messagingSenderId: '542980836794',
    projectId: 'rxmed0',
    storageBucket: 'rxmed0.appspot.com',
    iosBundleId: 'com.example.rxmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe-eoItkk-XtFNtwjoAMMl3q0uECVT6LU',
    appId: '1:542980836794:ios:19ea8253a34a61fc4b2183',
    messagingSenderId: '542980836794',
    projectId: 'rxmed0',
    storageBucket: 'rxmed0.appspot.com',
    iosBundleId: 'com.example.rxmed.RunnerTests',
  );
}
